-- Song media object metadata (binaries live in object storage)
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "audioObjectKey" TEXT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "audioContentType" TEXT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "audioSize" BIGINT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "audioUploadedAt" TIMESTAMP(3);

ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "coverObjectKey" TEXT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "coverContentType" TEXT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "coverSize" BIGINT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "coverUploadedAt" TIMESTAMP(3);

ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "musicVideoObjectKey" TEXT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "musicVideoContentType" TEXT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "musicVideoSize" BIGINT;
ALTER TABLE "Song" ADD COLUMN IF NOT EXISTS "musicVideoUploadedAt" TIMESTAMP(3);
